steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/snappy-byte-374310/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/snappy-byte-374310/testing']
